on: pull_request
jobs:
  validate:
    name: Validate json files with respective schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
          cache: true
      - name: Install jsonschema cmd
        run: go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest
      - name: Validate relayers.json
        run: jv schemas/relayer.schema.json relayers/*.json
